version: "2"

linters:
  enable:
    - errcheck
    - unused
    - staticcheck

linters-settings:
  errcheck:
    ignore: logger\.Sync$
  staticcheck:
    checks:
      - all
      - -SA1019

issues:
  exclude-rules:
    - linters:
        - errcheck
      text: "logger.Sync"
    - linters:
        - staticcheck
      text: "SA1019"
